### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by jski7** [bedapisl/fast-colorthief#2]
Hello, it seems that this script could help me a lot in my project.
I can not install it though.

>   Failed building wheel for fast-colorthief
  Running setup.py clean for fast-colorthief
Failed to build fast-colorthief
Installing collected packages: fast-colorthief
  Running setup.py install for fast-colorthief ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-eeuybk02/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9l08zz0c/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    copying fast_colorthief.py -> build/lib.linux-armv7l-3.7
    copying version.py -> build/lib.linux-armv7l-3.7
    running build_ext
    Traceback (most recent call last):
      File "/tmp/pip-req-build-eeuybk02/setup.py", line 28, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-eeuybk02/setup.py", line 84, in <module>
        zip_safe=False,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-eeuybk02/setup.py", line 32, in run
        ', '.join(e.name for e in self.extensions))
    RuntimeError: CMake must be installed to build the following extensions: fast_colorthief_backend
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-eeuybk02/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9l08zz0c/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-eeuybk02/

**Comment by bedapisl** [comment]
Hello, what operating system you are using?

The message is saying, that you need CMake. If you are on Ubuntu for example, you can install CMake with `apt-get install cmake`.

**Comment by bedapisl** [comment]
Closing :) If it still doesn't work for you, feel free to reopen :)
