### ISSUE TITLE
Down under the Windows installation has been an error, please, what's the reason, cmake also installed, still complains

### ISSUE THREAD

**Issue by wzgwy** [bedapisl/fast-colorthief#3]

**Comment by bedapisl** [comment]
Could you post the error message? I did not test it on windows, since I don't have an access to Windows machine.

**Comment by wzgwy** [comment]
(base) C:\Users\wwx964794\Desktop\pipinstall\fast-colorthief-master\fast-colorthief-master>pip install .
Processing c:\users\wwx964794\desktop\pipinstall\fast-colorthief-master\fast-colorthief-master
D:\soft\anaconda\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Requirement already satisfied: Pillow in d:\soft\anaconda\lib\site-packages (from fast-colorthief==0.0.4)
Requirement already satisfied: numpy in d:\soft\anaconda\lib\site-packages (from fast-colorthief==0.0.4)
Building wheels for collected packages: fast-colorthief
  Running setup.py bdist_wheel for fast-colorthief ... error
  Complete output from command D:\soft\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\WWX964~1\AppData\Local\Temp\tmp9a1s9733pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying fast_colorthief.py -> build\lib.win-amd64-3.6
  copying version.py -> build\lib.win-amd64-3.6
  running build_ext
  -- Building for: Visual Studio 16 2019
  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
  -- The C compiler identification is MSVC 19.28.29336.0
  -- The CXX compiler identification is MSVC 19.28.29336.0
  -- Check for working C compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
  -- Check for working C compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
  -- Check for working CXX compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:7 (add_subdirectory):
    The source directory

      C:/Users/wwx964794/AppData/Local/Temp/pip-_nypjozt-build/pybind11

    does not contain a CMakeLists.txt file.


  CMake Error at CMakeLists.txt:9 (pybind11_add_module):
    Unknown CMake command "pybind11_add_module".


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/wwx964794/AppData/Local/Temp/pip-_nypjozt-build/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\WWX964~1\AppData\Local\Temp\pip-_nypjozt-build\setup.py", line 84, in <module>
      zip_safe=False,
    File "D:\soft\anaconda\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "D:\soft\anaconda\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\soft\anaconda\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "D:\soft\anaconda\lib\site-packages\wheel\bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "D:\soft\anaconda\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "D:\soft\anaconda\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\soft\anaconda\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\WWX964~1\AppData\Local\Temp\pip-_nypjozt-build\setup.py", line 40, in run
      self.build_extension(ext)
    File "C:\Users\WWX964~1\AppData\Local\Temp\pip-_nypjozt-build\setup.py", line 66, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "D:\soft\anaconda\lib\subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build\\build\\lib.win-amd64-3.6\\', '-DPYTHON_EXECUTABLE=D:\\soft\\anaconda\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build\\build\\lib.win-amd64-3.6\\', '-A', 'x64']' returned non-zero exit status 1.

  ----------------------------------------
  Failed building wheel for fast-colorthief
  Running setup.py clean for fast-colorthief
Failed to build fast-colorthief
Installing collected packages: fast-colorthief
  Running setup.py install for fast-colorthief ... error
    Complete output from command D:\soft\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\WWX964~1\AppData\Local\Temp\pip-hyfi5oev-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying fast_colorthief.py -> build\lib.win-amd64-3.6
    copying version.py -> build\lib.win-amd64-3.6
    running build_ext
    -- Building for: Visual Studio 16 2019
    -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
    -- The C compiler identification is MSVC 19.28.29336.0
    -- The CXX compiler identification is MSVC 19.28.29336.0
    -- Check for working C compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
    -- Check for working C compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
    -- Check for working CXX compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:7 (add_subdirectory):
      The source directory

        C:/Users/wwx964794/AppData/Local/Temp/pip-_nypjozt-build/pybind11

      does not contain a CMakeLists.txt file.


    CMake Error at CMakeLists.txt:9 (pybind11_add_module):
      Unknown CMake command "pybind11_add_module".


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/wwx964794/AppData/Local/Temp/pip-_nypjozt-build/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WWX964~1\AppData\Local\Temp\pip-_nypjozt-build\setup.py", line 84, in <module>
        zip_safe=False,
      File "D:\soft\anaconda\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "D:\soft\anaconda\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\soft\anaconda\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\soft\anaconda\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\soft\anaconda\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "D:\soft\anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\soft\anaconda\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\soft\anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\WWX964~1\AppData\Local\Temp\pip-_nypjozt-build\setup.py", line 40, in run
        self.build_extension(ext)
      File "C:\Users\WWX964~1\AppData\Local\Temp\pip-_nypjozt-build\setup.py", line 66, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "D:\soft\anaconda\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build\\build\\lib.win-amd64-3.6\\', '-DPYTHON_EXECUTABLE=D:\\soft\\anaconda\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build\\build\\lib.win-amd64-3.6\\', '-A', 'x64']' returned non-zero exit status 1.

    ----------------------------------------
Command "D:\soft\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-_nypjozt-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\WWX964~1\AppData\Local\Temp\pip-hyfi5oev-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\WWX964~1\AppData\Local\Temp\pip-_nypjozt-build\
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by bedapisl** [comment]
Hello, would you try:
```
git submodule update --init --recursive
```
before
```
pip install .
```

**Comment by wzgwy** [comment]
Hello, now come across this wrong
(base) C:\Users\wwx964794\Desktop\pipinstall\fast-colorthief>pip install .
Processing c:\users\wwx964794\desktop\pipinstall\fast-colorthief
D:\soft\anaconda\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Requirement already satisfied: Pillow in d:\soft\anaconda\lib\site-packages (from fast-colorthief==0.0.4)
Requirement already satisfied: numpy in d:\soft\anaconda\lib\site-packages (from fast-colorthief==0.0.4)
Building wheels for collected packages: fast-colorthief
  Running setup.py bdist_wheel for fast-colorthief ... error
  Failed building wheel for fast-colorthief
  Running setup.py clean for fast-colorthief
Failed to build fast-colorthief
Installing collected packages: fast-colorthief
  Running setup.py install for fast-colorthief ... error
Exception:
Traceback (most recent call last):
  File "D:\soft\anaconda\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\soft\anaconda\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\soft\anaconda\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "D:\soft\anaconda\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "D:\soft\anaconda\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "D:\soft\anaconda\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "D:\soft\anaconda\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by wzgwy** [comment]
(base) C:\Users\wwx964794\Desktop\pipinstall\fast-colorthief>pip install .
Processing c:\users\wwx964794\desktop\pipinstall\fast-colorthief
D:\soft\anaconda\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Requirement already satisfied: Pillow in d:\soft\anaconda\lib\site-packages (from fast-colorthief==0.0.4)
Requirement already satisfied: numpy in d:\soft\anaconda\lib\site-packages (from fast-colorthief==0.0.4)
Building wheels for collected packages: fast-colorthief
  Running setup.py bdist_wheel for fast-colorthief ... error
  Failed building wheel for fast-colorthief
  Running setup.py clean for fast-colorthief
  Failed cleaning build dir for fast-colorthief
Failed to build fast-colorthief
Installing collected packages: fast-colorthief
  Running setup.py install for fast-colorthief ... error
    Complete output from command D:\soft\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-qvhr3dhh-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\WWX964~1\AppData\Local\Temp\pip-y2js9it6-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build\lib.win-amd64-3.6
    copying fast_colorthief.py -> build\lib.win-amd64-3.6
    copying version.py -> build\lib.win-amd64-3.6
    running build_ext
    -- Building for: Visual Studio 16 2019
    -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
    -- The C compiler identification is MSVC 19.28.29336.0
    -- The CXX compiler identification is MSVC 19.28.29336.0
    -- Check for working C compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
    -- Check for working C compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - failed
    -- Detecting C compile features
    -- Detecting C compile features - failed
    -- Check for working CXX compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
    -- Check for working CXX compiler: D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe -- broken
    CMake Error at D:/soft/anaconda/Lib/site-packages/cmake/data/share/cmake-3.14/Modules/CMakeTestCXXCompiler.cmake:53 (message):
      The C++ compiler

        "D:/soft/vs2019/community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"

      is not able to compile a simple test program.

      It fails with the following output:

        Change Dir: C:/Users/wwx964794/AppData/Local/Temp/pip-qvhr3dhh-build/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeTmp

        Run Build Command(s):D:/soft/vs2019/community/MSBuild/Current/Bin/MSBuild.exe cmTC_b53b6.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
        版权所有(C) Microsoft Corporation。保留所有权利。

        MSBUILD : error MSB1009: 项目文件不存在。
        开关:cmTC_b53b6.vcxproj




      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:2 (project)


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/wwx964794/AppData/Local/Temp/pip-qvhr3dhh-build/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/wwx964794/AppData/Local/Temp/pip-qvhr3dhh-build/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WWX964~1\AppData\Local\Temp\pip-qvhr3dhh-build\setup.py", line 84, in <module>
        zip_safe=False,
      File "D:\soft\anaconda\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "D:\soft\anaconda\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\soft\anaconda\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\soft\anaconda\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\soft\anaconda\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "D:\soft\anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\soft\anaconda\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\soft\anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\soft\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\WWX964~1\AppData\Local\Temp\pip-qvhr3dhh-build\setup.py", line 40, in run
        self.build_extension(ext)
      File "C:\Users\WWX964~1\AppData\Local\Temp\pip-qvhr3dhh-build\setup.py", line 66, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "D:\soft\anaconda\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-qvhr3dhh-build', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-qvhr3dhh-build\\build\\lib.win-amd64-3.6\\', '-DPYTHON_EXECUTABLE=D:\\soft\\anaconda\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-qvhr3dhh-build\\build\\lib.win-amd64-3.6\\', '-A', 'x64']' returned non-zero exit status 1.

    ----------------------------------------
Exception:
Traceback (most recent call last):
  File "D:\soft\anaconda\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "D:\soft\anaconda\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "D:\soft\anaconda\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "D:\soft\anaconda\lib\site-packages\pip\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "D:\soft\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-qvhr3dhh-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\WWX964~1\AppData\Local\Temp\pip-y2js9it6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\WWX964~1\AppData\Local\Temp\pip-qvhr3dhh-build\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\soft\anaconda\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\soft\anaconda\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "D:\soft\anaconda\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "D:\soft\anaconda\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "D:\soft\anaconda\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "D:\soft\anaconda\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "D:\soft\anaconda\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "D:\soft\anaconda\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "D:\soft\anaconda\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "D:\soft\anaconda\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "D:\soft\anaconda\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\soft\anaconda\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\soft\anaconda\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\WWX964~1\\AppData\\Local\\Temp\\pip-qvhr3dhh-build'
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
