### ISSUE TITLE
Can't get fast-colorthief to build on Windows (Python 3.11.6). Latest CMake is installed.

### ISSUE THREAD

**Issue by fmotion1** [bedapisl/fast-colorthief#30]
Output from `pip3 install .`

```plaintext
(DomColorsVENV) 11-29 09:27:07 D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\fast-colorthief [master ≡ +1 ~0 -0 !]> pip3 install .
Processing d:\dev\powershell\vsysmodules\vsysimgops\bin\fast-colorthief
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Pillow in d:\dev\powershell\vsysmodules\vsysimgops\bin\domcolorsvenv\lib\site-packages (from fast-colorthief==0.0.5) (10.1.0)
Requirement already satisfied: numpy in d:\dev\powershell\vsysmodules\vsysimgops\bin\domcolorsvenv\lib\site-packages (from fast-colorthief==0.0.5) (1.26.2)
Building wheels for collected packages: fast-colorthief
  Building wheel for fast-colorthief (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      copying fast_colorthief.py -> build\lib.win-amd64-cpython-311
      copying version.py -> build\lib.win-amd64-cpython-311
      running build_ext
      D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\fast-colorthief\setup.py:35: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      CMake Error at CMakeLists.txt:2 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\fast-colorthief\setup.py", line 70, in <module>
          setup(
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\DomColorsVENV\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\fast-colorthief\setup.py", line 40, in run
          self.build_extension(ext)
        File "D:\Dev\Powershell\VSYSModules\VSYSImgOps\bin\fast-colorthief\setup.py", line 66, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "C:\Users\futur\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'D:\\Dev\\Powershell\\VSYSModules\\VSYSImgOps\\bin\\fast-colorthief', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Dev\\Powershell\\VSYSModules\\VSYSImgOps\\bin\\fast-colorthief\\build\\lib.win-amd64-cpython-311\\', '-DPYTHON_EXECUTABLE=D:\\Dev\\Powershell\\VSYSModules\\VSYSImgOps\\bin\\DomColorsVENV\\Scripts\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=D:\\Dev\\Powershell\\VSYSModules\\VSYSImgOps\\bin\\fast-colorthief\\build\\lib.win-amd64-cpython-311\\', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fast-colorthief
  Running setup.py clean for fast-colorthief
Failed to build fast-colorthief
ERROR: Could not build wheels for fast-colorthief, which is required to install pyproject.toml-based projects
```

Is there anything I can do to get this working?

**Comment by bedapisl** [comment]
It has been more than a month, so I am closing this. We can reopen if the issue persists.
