### ISSUE TITLE
Request: Apple Silicon support

### ISSUE THREAD

**Issue by mmoollllee** [bedapisl/fast-colorthief#39]
Hey :)
Thanks for your work!
I'm trying to run it on Apple M3 Processor and get the following message with Python 3.11.
I guess Apple Silicon is not yet supported?

```
Traceback (most recent call last):
  File "/Users/dev/app.py", line 15, in <module>
    import upload
  File "/Users/dev/upload.py", line 7, in <module>
    import fast_colorthief
  File "/Users/dev/venv/lib/python3.11/site-packages/fast_colorthief.py", line 2, in <module>
    import fast_colorthief_backend
ImportError: dlopen(/Users/dev/venv/lib/python3.11/site-packages/fast_colorthief_backend.cpython-311-darwin.so, 0x0002): tried: '/Users/dev/venv/lib/python3.11/site-packages/fast_colorthief_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dev/venv/lib/python3.11/site-packages/fast_colorthief_backend.cpython-311-darwin.so' (no such file), '/Users/dev/venv/lib/python3.11/site-packages/fast_colorthief_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by bedapisl** [comment]
Hello, I don't have access to Apple M3 Processor for testing so I don't know if I will be able to help you.

The only idea I have right now is that if you have installed this with plain `pip install fast_colorthief`, you should try installation from source. Install CMake and run 
```
git clone https://github.com/bedapisl/fast-colorthief
cd fast-colorthief
git submodule update --init --recursive
pip3 install .
```

**Comment by foureyedraven** [comment]
Hi, just wanted to add that I have M1 and I did the local build with CMake route, and it worked :) Thank you for making this lib
