### ISSUE TITLE
Unable to install [Linux]

### ISSUE THREAD

**Issue by Galo223344** [bedapisl/fast-colorthief#5]
On ubuntu, when I try running `pip install fast-colorthief` I get the following error
```
root@Gtadictos21:/home/p/fast-colorthief# pip install fast-colorthief
Collecting fast-colorthief
  Using cached fast-colorthief-0.0.1.tar.gz (2.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jhs05n8m/fast-colorthief/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jhs05n8m/fast-colorthief/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-jhs05n8m/fast-colorthief/pip-egg-info
         cwd: /tmp/pip-install-jhs05n8m/fast-colorthief/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jhs05n8m/fast-colorthief/setup.py", line 12, in <module>
        import fast_colorthief
      File "/tmp/pip-install-jhs05n8m/fast-colorthief/fast_colorthief.py", line 2, in <module>
        import fast_colorthief_backend
    ModuleNotFoundError: No module named 'fast_colorthief_backend'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

So I tried the other method, I ran `git clone`, then I ran `pip install .` and I got _this_ error instead:
```
root@Gtadictos21:/home/p/fast-colorthief# pip3 install .                        Processing /home/p/fast-colorthief
Requirement already satisfied: Pillow in /usr/local/lib/python3.8/dist-packages (from fast-colorthief==0.0.4) (8.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from fast-colorthief==0.0.4) (1.20.3)
Building wheels for collected packages: fast-colorthief
  Building wheel for fast-colorthief (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kdvmaqbw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kdvmaqbw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qni4v_ee
       cwd: /tmp/pip-req-build-kdvmaqbw/
  Complete output (67 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  copying fast_colorthief.py -> build/lib.linux-x86_64-3.8
  copying version.py -> build/lib.linux-x86_64-3.8
  running build_ext
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:7 (add_subdirectory):
    The source directory

      /tmp/pip-req-build-kdvmaqbw/pybind11

    does not contain a CMakeLists.txt file.


  CMake Error at CMakeLists.txt:9 (pybind11_add_module):
    Unknown CMake command "pybind11_add_module".


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-kdvmaqbw/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-kdvmaqbw/setup.py", line 70, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-kdvmaqbw/setup.py", line 40, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-kdvmaqbw/setup.py", line 66, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-kdvmaqbw', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-kdvmaqbw/build/lib.linux-x86_64-3.8/', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for fast-colorthief
  Running setup.py clean for fast-colorthief
Failed to build fast-colorthief
Installing collected packages: fast-colorthief
    Running setup.py install for fast-colorthief ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kdvmaqbw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kdvmaqbw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bza9qjgv/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/fast-colorthief
         cwd: /tmp/pip-req-build-kdvmaqbw/
    Complete output (69 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying fast_colorthief.py -> build/lib.linux-x86_64-3.8
    copying version.py -> build/lib.linux-x86_64-3.8
    running build_ext
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:7 (add_subdirectory):
      The source directory

        /tmp/pip-req-build-kdvmaqbw/pybind11

      does not contain a CMakeLists.txt file.


    CMake Error at CMakeLists.txt:9 (pybind11_add_module):
      Unknown CMake command "pybind11_add_module".


    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-kdvmaqbw/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-kdvmaqbw/setup.py", line 70, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-kdvmaqbw/setup.py", line 40, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-kdvmaqbw/setup.py", line 66, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-kdvmaqbw', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-kdvmaqbw/build/lib.linux-x86_64-3.8/', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kdvmaqbw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kdvmaqbw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bza9qjgv/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/fast-colorthief Check the logs for full command output.

```

Running sudo `apt-get install cmake` just returns `cmake is already the newest version (3.16.3-1ubuntu1).`

Any help is appreciated.

**Comment by Galo223344** [comment]
Issue fixed by following instructions of issue #3 

> > Hello, would you try:
> > ```
> > git submodule update --init --recursive
> > ```
> >    
> > before
> > ```
> > pip install .
> > ```
> I had the same error, but I used pip3 install . and its working now
